//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllStatu
    {
        public int Id { get; set; }
        public string SName { get; set; }
        public string SType { get; set; }
        public string SCode { get; set; }
        public string SNotes { get; set; }
    }
}
