//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIDetail
    {
        public int Id { get; set; }
        public string BaseUrl { get; set; }
        public string Describe { get; set; }
        public string Method { get; set; }
        public string Name { get; set; }
    }
}
