//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeHistory
    {
        public string Id { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CaseCode { get; set; }
        public string Messenge { get; set; }
        public string PStatus { get; set; }
        public string WareHouse { get; set; }
        public string WareHouseType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string WareRelative { get; set; }
        public string WareRelativeType { get; set; }
        public string StaffHelp { get; set; }
        public string UserLogin { get; set; }
        public string LocationStaff { get; set; }
        public string StaffHelpIssue { get; set; }
        public Nullable<int> IsSuccess { get; set; }
        public string WareHouseName { get; set; }
        public string WareRelativeName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
    }
}
