//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHistory
    {
        public string Id { get; set; }
        public string Barcode { get; set; }
        public string PStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserSend { get; set; }
        public string WType { get; set; }
        public string WName { get; set; }
        public string WCode { get; set; }
        public string BoxCode { get; set; }
        public string ProductCode { get; set; }
        public string CaseCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
}
