//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffCalendarC2
    {
        public string Id { get; set; }
        public Nullable<int> CDay { get; set; }
        public Nullable<int> CMonth { get; set; }
        public Nullable<int> CYear { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> CheckPlan { get; set; }
        public Nullable<int> CheckIn { get; set; }
        public string CId { get; set; }
    
        public virtual C2Info C2Info { get; set; }
        public virtual HaiStaff HaiStaff { get; set; }
    }
}
