//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ScanImport { get; set; }
        public Nullable<int> ScanExport { get; set; }
        public Nullable<int> InputReceive { get; set; }
        public string WareReceive { get; set; }
        public Nullable<int> IsScanBox { get; set; }
    }
}
