//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarType
    {
        public string Id { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Compel { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> TGroup { get; set; }
        public string Name { get; set; }
        public Nullable<int> InPlan { get; set; }
        public Nullable<int> OutPlan { get; set; }
        public Nullable<int> Flexible { get; set; }
        public string GroupType { get; set; }
    }
}
