//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CInfoCommon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CInfoCommon()
        {
            this.AgencySavePoints = new HashSet<AgencySavePoint>();
            this.C1Info = new HashSet<C1Info>();
            this.C2Info = new HashSet<C2Info>();
            this.EventCustomers = new HashSet<EventCustomer>();
            this.EventCustomerFarmers = new HashSet<EventCustomerFarmer>();
            this.FarmerInfoes = new HashSet<FarmerInfo>();
            this.MSGPoints = new HashSet<MSGPoint>();
            this.SaveAgencyShopImages = new HashSet<SaveAgencyShopImage>();
            this.HaiOrders = new HashSet<HaiOrder>();
        }
    
        public string Id { get; set; }
        public string CName { get; set; }
        public string IdentityCard { get; set; }
        public string AddressInfo { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Notes { get; set; }
        public string UserLogin { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CType { get; set; }
        public string ProvinceName { get; set; }
        public string DistrictName { get; set; }
        public string BranchCode { get; set; }
        public string CCode { get; set; }
        public string CDeputy { get; set; }
        public string BankAccount { get; set; }
        public string BankAccountHolder { get; set; }
        public string BackName { get; set; }
        public string TaxCode { get; set; }
        public string BusinessLicense { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string CRank { get; set; }
        public string WardName { get; set; }
        public string Country { get; set; }
        public string BirthDay { get; set; }
        public string ProvinceCode { get; set; }
        public string AgencyType { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencySavePoint> AgencySavePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1Info> C1Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C2Info> C2Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCustomer> EventCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCustomerFarmer> EventCustomerFarmers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerInfo> FarmerInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSGPoint> MSGPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveAgencyShopImage> SaveAgencyShopImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaiOrder> HaiOrders { get; set; }
        public virtual AgencyType AgencyType1 { get; set; }
    }
}
