//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerInfo
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string FarmerName { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsLock { get; set; }
        public string InfoId { get; set; }
        public string TreeType { get; set; }
        public string Tree { get; set; }
        public string Acreage { get; set; }
    
        public virtual CInfoCommon CInfoCommon { get; set; }
    }
}
