//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaiDepartment
    {
        public HaiDepartment()
        {
            this.HaiStaffs = new HashSet<HaiStaff>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<HaiStaff> HaiStaffs { get; set; }
    }
}
