//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSGPoint()
        {
            this.MSGPointEvents = new HashSet<MSGPointEvent>();
        }
    
        public string Id { get; set; }
        public string CInfoId { get; set; }
        public string UserLogin { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public string Barcode { get; set; }
        public string ProductId { get; set; }
        public string MSGType { get; set; }
    
        public virtual CInfoCommon CInfoCommon { get; set; }
        public virtual ProductInfo ProductInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSGPointEvent> MSGPointEvents { get; set; }
    }
}
