//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldKeySave
    {
        public string Id { get; set; }
        public string OldCode { get; set; }
        public string NewCode { get; set; }
        public string CodeType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
