//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public ProductInfo()
        {
            this.EventProducts = new HashSet<EventProduct>();
            this.MSGPoints = new HashSet<MSGPoint>();
            this.ProductSeris = new HashSet<ProductSeri>();
            this.PTrackings = new HashSet<PTracking>();
        }
    
        public string Id { get; set; }
        public string PName { get; set; }
        public string PCode { get; set; }
        public string Material { get; set; }
        public string Utility { get; set; }
        public string Unit { get; set; }
        public string Producer { get; set; }
        public string PGroup { get; set; }
        public string PMajor { get; set; }
        public string Acronym { get; set; }
        public string CardPoint { get; set; }
        public string BoxPoint { get; set; }
        public Nullable<int> IsLock { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> QuantityBox { get; set; }
        public Nullable<int> IsBox { get; set; }
    
        public virtual ICollection<EventProduct> EventProducts { get; set; }
        public virtual ICollection<MSGPoint> MSGPoints { get; set; }
        public virtual ICollection<ProductSeri> ProductSeris { get; set; }
        public virtual ICollection<PTracking> PTrackings { get; set; }
    }
}
