//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAIAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetLocation
    {
        public string Id { get; set; }
        public string AgencyCode { get; set; }
        public string OldLocation { get; set; }
        public string NewLocation { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> IsAppove { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserLogin { get; set; }
    
        public virtual HaiStaff HaiStaff { get; set; }
    }
}
