//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2C1
    {
        public string Id { get; set; }
        public string C2Code { get; set; }
        public string C1Code { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
