//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecorImage
    {
        public string Id { get; set; }
        public Nullable<int> DaySend { get; set; }
        public Nullable<int> MonthSend { get; set; }
        public Nullable<int> YearSend { get; set; }
        public string AgencyCode { get; set; }
        public string AgencyType { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.TimeSpan> CreateTime { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string DecorGroup { get; set; }
        public string StaffId { get; set; }
    
        public virtual HaiStaff HaiStaff { get; set; }
    }
}
