//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncRole
    {
        public int FuncId { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> IsAll { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual FuncInfo FuncInfo { get; set; }
    }
}
