//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIDetail
    {
        public string Id { get; set; }
        public string PlanPoint { get; set; }
        public string Perform { get; set; }
        public string PlanPercent { get; set; }
        public string Point { get; set; }
        public string StaffKPIId { get; set; }
        public string KPIWorkId { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual KPIWork KPIWork { get; set; }
        public virtual StaffKPI StaffKPI { get; set; }
    }
}
