//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPITemplate
    {
        public string KPIWorkId { get; set; }
        public string KPITypeId { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual KPIType KPIType { get; set; }
        public virtual KPIWork KPIWork { get; set; }
    }
}
