//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductHistory
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserAction { get; set; }
        public string Notes { get; set; }
        public string StaffId { get; set; }
    
        public virtual HaiOrder HaiOrder { get; set; }
        public virtual ProductInfo ProductInfo { get; set; }
        public virtual HaiStaff HaiStaff { get; set; }
    }
}
