//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStaffProcess
    {
        public OrderStaffProcess()
        {
            this.OrderStaffs = new HashSet<OrderStaff>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<OrderStaff> OrderStaffs { get; set; }
    }
}
