//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayType
    {
        public PayType()
        {
            this.HaiOrders = new HashSet<HaiOrder>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<HaiOrder> HaiOrders { get; set; }
    }
}
