//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    
    public partial class report_checkin_general_Result2
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Code { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> AllAgency { get; set; }
        public Nullable<int> AllAgencyCheckIn { get; set; }
        public Nullable<int> AllDayCSBH { get; set; }
        public Nullable<int> AllAgencyOrder { get; set; }
        public Nullable<double> AllOrderPrice { get; set; }
        public Nullable<int> AllOrder { get; set; }
    }
}
