//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSHistory
    {
        public string Id { get; set; }
        public string PhoneNumber { get; set; }
        public string ContentSend { get; set; }
        public string ContentReturn { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string AgencyType { get; set; }
        public Nullable<int> Success { get; set; }
    }
}
