//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffWithC2
    {
        public string C2Id { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> GroupChoose { get; set; }
    
        public virtual C2Info C2Info { get; set; }
        public virtual HaiStaff HaiStaff { get; set; }
    }
}
