//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAgencyId
    {
        public string Id { get; set; }
        public Nullable<int> IsUse { get; set; }
        public Nullable<int> CountNumber { get; set; }
        public string TypeStore { get; set; }
    }
}
