//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeNotPermiss
    {
        public string Id { get; set; }
        public string Barcode { get; set; }
        public string CaseCode { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserUpload { get; set; }
        public string BranchCode { get; set; }
        public string ProductName { get; set; }
        public string ProductBarcode { get; set; }
    }
}
