//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaiArea
    {
        public HaiArea()
        {
            this.CInfoCommons = new HashSet<CInfoCommon>();
            this.EventAreas = new HashSet<EventArea>();
            this.EventAreaFarmers = new HashSet<EventAreaFarmer>();
            this.HaiBranches = new HashSet<HaiBranch>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<CInfoCommon> CInfoCommons { get; set; }
        public virtual ICollection<EventArea> EventAreas { get; set; }
        public virtual ICollection<EventAreaFarmer> EventAreaFarmers { get; set; }
        public virtual ICollection<HaiBranch> HaiBranches { get; set; }
    }
}
