//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeInfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string TreeType { get; set; }
        public string Acreage { get; set; }
        public string STT { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
